# Generated by Django 6.0 on 2026-01-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='capture_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
